### ISSUE TITLE
Category Records/ Category Tab in FAL/Image edit Form not displayed for BE editors

### ISSUE THREAD

**Issue by DamselDefiler** [fabarea/media#10]
I cant find a permission constellation on a group to allow users the categories in media extensions.
If a image is uploaded and the metadata edited the categoires tab does not show.

BE Group for that users have , mount on some categories, has read and modify table categories for that matter. 

As an admin there is no problem, the form displays and working just fine.

**Comment by fabarea** [comment]
In a be_groups (pid = 0), you must have the following settings

![screenshot 2015-04-02 17 08 26](https://cloud.githubusercontent.com/assets/620730/6966695/33dfde16-d95b-11e4-8fde-85d8fd3ba6ad.png)
![screenshot 2015-04-02 17 09 36](https://cloud.githubusercontent.com/assets/620730/6966698/375c2e50-d95b-11e4-9290-94e045ee61ee.png)
