### ISSUE TITLE
The way registering a wizard in TCA has changed in 6.2 and was removed in CMS 7

### ISSUE THREAD

**Issue by stekna** [fabarea/media#101]
with activated media 4.0.1 (and typo3 7.6.1 or 7.6.2) the following error occurs when i want to edit a filestorage. i cant find out which files from media extension is affected.

Uncaught TYPO3 Exception
#1437750231: The way registering a wizard in TCA has changed in 6.2 and was removed in CMS 7. Please set module[name]=module_name instead of using script=path/to/script.php in your TCA. [More information](https://wiki.typo3.org/Exception/CMS/1437750231)

InvalidArgumentException thrown in file
/www/htdocs/xxuserxx/typo3_src-7.6.2/typo3/sysext/backend/Classes/Form/Element/AbstractFormElement.php in line 156.

**Comment by fabarea** [comment]
Should be fixed in master.

**Comment by ghost** [comment]
is this still broken in master?
I'm getting the error with typo3 7.6.4 and media 4.0.3
sys_file_storage.php still contains lines with 'script' => 'wizard_edit.php' like in
https://github.com/fabarea/media/blob/master/Configuration/TCA/Overrides/sys_file_storage.php#L108

replacing all of them with 'module' => array('name' => 'wizard_edit') seems to fix #1437750231
(like in the patch from advOpk)
