### ISSUE TITLE
Fileupload to other storage as selected

### ISSUE THREAD

**Issue by stekna** [fabarea/media#102]
with activated setting "Load the folder tree", file upload to the respective filestorage in media is fine.
but if i deactivate "load folder tree", the fileupload is done to my first filestorage (user_upload) an not to the selected one.

e.g. i upload a file with media in selected filestorage "storagepdf" and the upload is done, but not saved in "storagepdf". the file instead is saved in "user_upload" (= my first storage).

**Comment by stekna** [comment]
now i tested in a complete fresh typo3 7.6.2 installation.
there is the same issue.

**Comment by fabarea** [comment]
I suspect a cache issue. FYI, I will make a new release of Media by then end of the week or beginning of next one, can you re-test then. The error should be gone.

**Comment by stekna** [comment]
it works now , thanks for your effort!
