### ISSUE TITLE
[Content] Text & Image and drag & drop

### ISSUE THREAD

**Issue by Simperfit** [fabarea/media#103]
Greets,

We are using media + vidi as the media manager in our typo3 website
![capture d ecran 2015-12-31 a 15 21 58](https://cloud.githubusercontent.com/assets/3451634/12065147/66b20942-afd2-11e5-85a9-7aab1a91c797.png)

When using the Add images button on a txt+img or img tt_content we doesn't have the vidi GUI neither we cannot drag and drop images here.

![capture d ecran 2015-12-31 a 15 22 02](https://cloud.githubusercontent.com/assets/3451634/12065146/66af6ab6-afd2-11e5-80a6-715d134785ae.png)

Are we doing something wrong  or is this a real bug ?

**Comment by fabarea** [comment]
Have you clicked the according option in the EM of Media? Reload the BE afterwards.

```
Use the Media file picker [basic.has_media_file_picker]

If checked, default file picker will be replaced by the Media file picker.
```

**Comment by Simperfit** [comment]
It does help with the first part but we cannot drag&drop images directly in the content like this

![Drag and drop in the typo3 documentation about FAL](https://cloud.githubusercontent.com/assets/3451634/12065649/539e7d78-afdb-11e5-8dc6-363449a86862.png)
When we de-activate media we get that button back.

**Comment by fabarea** [comment]
You can drag & drop in the Media module (i.e. popup). Direct drag & drop as you wish is still missing...
