### ISSUE TITLE
PHP Fatal Error Class Fab\Media\Facet\ActionPermissionFacet

### ISSUE THREAD

**Issue by liveman1** [fabarea/media#106]
When updating media to version 3.7.2,

I get the following error in the frontend:
Fatal error: Class Fab\Media\Facet\ActionPermissionFacet contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Fab\Vidi\Facet\FacetInterface::getFieldNameAndPath) in /home/u01242813840/public_html/typo3conf/ext/media/Classes/Facet/ActionPermissionFacet.php on line 256

**Comment by fabarea** [comment]
Assuming you are on TYPO3 7: update Vidi + Media followed by a deep clear cache. That should work.
