### ISSUE TITLE
Missing Storage Selectbox

### ISSUE THREAD

**Issue by jazzica** [fabarea/media#109]
Hi,

with the latest media versions I can't find the possibility to change the file storage as was supported by earlier versions.

![bildschirmfoto 2016-01-16 um 14 34 52](https://cloud.githubusercontent.com/assets/4162007/12372619/0c9fd0f8-bc5f-11e5-9bf7-efcd33909657.png) 

Am I missing a configuration setting or do I have to display the folder tree to switch storages? 

Thanks for the support.
Jessica

**Comment by mischka** [comment]
+1

**Comment by mischka** [comment]
Hello Fabien,

I think there is a typo on line https://github.com/fabarea/media/blob/master/Classes/Module/MediaModule.php#L266 because the negation of the config value makes no sense. Or do you have another explanation for the exclamation mark / negation?
regards

Kay

**Comment by fabarea** [comment]
It could be. I will double check when working on this one. FYI, I have this issue on my radar. I also need a fix for one of our setup.

**Comment by mischka** [comment]
In version 3.7.2 you only call the method here https://github.com/fabarea/media/blob/master/Classes/View/Menu/StorageMenu.php#L55
