### ISSUE TITLE
No module "content_VidiSysFileM1" could be found because wrong TBE_MODULES key

### ISSUE THREAD

**Issue by mischka** [fabarea/media#112]
I use version 3.7.2 and the $configuration['has_folder_tree']['value'] is false, so the $defaultMainModule is 'content' .
If I try to edit the storage or choose a file in a FCE I always get this error:

**#1294585070: No module "content_VidiSysFileM1" could be found.**

And this is "correct" because if I look in my configuration the module-key does not exists / is wrong `VidiContent_VidiSysFileM1`

$GLOBALS['TBE_MODULES'](BE Modules) :

[content]=VidiFeUsersM1,VidiFeGroupsM1
[user]=setup,MediaM1
[VidiContent]=VidiSysFileM1 (should be in the content-module or not?)

Under:

```
[_configuration]
  [content_VidiFeGroupsM1]
  [content_VidiFeUsersM1]
  [user_MediaM1]
  [VidiContent_VidiSysFileM1]  but should `[content_VidiSysFileM1] or?
```

Has someone an idea why the is registered with the wrong signature?

Maybe there is a problem with the ModuleLoader::register

https://github.com/fabarea/vidi/blob/1.3.1/Classes/Module/ModuleLoader.php#L825
or
https://github.com/fabarea/media/blob/3.7.x/Classes/Module/VidiModule.php#L27
 to VidiContent_VidiSysFileM1

**Comment by fabarea** [comment]
I suspect a cache issue. FYI, I will make a new release of Media by then end of the week or beginning of next one, can you re-test then. The error should be gone.

**Comment by mischka** [comment]
Please offer the release for the 3.7.x branch too.

**Comment by fabarea** [comment]
Very difficult! Media >= 4 is for TYPO3 7 and the code base is (unfortunately for your case) too different from the TYPO3 6.2 compatible version... They are too many differences. However, the error mentionned on this ticket looks weird for me... I never faced it.
