### ISSUE TITLE
TYPO3 7 - Load RTE configuration

### ISSUE THREAD

**Issue by martinhummer** [fabarea/media#118]
this setting is ignored in typo3 7.4 and the buttons "imageeditor" and "linkcreator" are not shown.

i'm using dev-master of media and vidi.

related to #114 #113

**Comment by fabarea** [comment]
I just double checked and if I strip all configuration of the RTE, I correctly get my news buttons (ImageEditor + LinkCreator). I suspect your RTE configuration is overridden somewhere. Nevertheless I will be committing a path as I found a bug when integrating the 2 plugins within the RTE.

```
ATTENTION! there is a bug (or I missed something) with TYPO3 7 LTS where the same JavaScript files 
must be placed in two locations, one in Media, one in the Core. Consider executing this command from
 your document root: 
cp typo3conf/ext/media/Resources/Public/JavaScript/Plugins/{LinkCreator.js,ImageEditor.js} typo3/sysext/rtehtmlarea/Resources/Public/JavaScript/Plugins
```

BTW, consider TYPO3 7.6 LTS

**Comment by martinhummer** [comment]
after i copied the two javascript files manually as you mentioned, everything works as expected!
thanks for your effort!
