### ISSUE TITLE
I could not save your preferences, something went wrong in the Ajax request!

### ISSUE THREAD

**Issue by ghost** [fabarea/media#120]
Hi Fabien,
what does it means, when load the media Modul in BE:
"Communication error
I could not save your preferences, something went wrong in the Ajax request!"
Since some versions always pop it up this Red Error Message.
Greetings and Thank you for this nice ext.

**Comment by fabarea** [comment]
The preferences means here the module state (visible column, sort, filter, ...) which are saved in the background.

Could you visit the install tool > database compare. I suspect a missing field.
