### ISSUE TITLE
Variants missing in new version 

### ISSUE THREAD

**Issue by sivaprasad88** [fabarea/media#121]
Hi All,

I am working on TYPO3 7 and media extension . The problem which I am facing now is , in earlier version of media extension , when we upload a new images it will resize to a set predefined dimensions(Variants).But with new media extension this feature is missing . Is this feature still present in this extension . 

BR
Siva

**Comment by raphaelstolt** [comment]
Can confirm this problem with Typo3 `7.6.4` and latest `typo3-ter/media` installed via Composer.

**Comment by fabarea** [comment]
Variant was introduced in TYPO3 6.0 and 6.1 for RTE purposes. At that time, the RTE was not able to dynamically generates images for a specific width and height. Therefore the concept of Variant was introduced to workaround and solved this use case. The situation however changed in TYPO3 6.2 where the RTE generates Processed File and Variant had consequently no more reasons to exist as the Core was providing a solution and was removed. It could not be foreseen ; sorry for the inconvenience.
