### ISSUE TITLE
Fatal error: VIDI - Version 2.0.3.

### ISSUE THREAD

**Issue by Alexander-Alexander** [fabarea/media#122]
Dear Ecodev,
i just updated to T3 7.6.4.
Then i updated from vidi ext. from 2.0.1. to vidi 2.0.3 - after that i updated media ext from 4.0.1. to 4.0.2.
Before the updates, everything was runnig fine - now i get the following erroer, when i try to open the media backend from the typo3 backend: 

Fatal error: Call to undefined method Fab\Vidi\Persistence\Matcher::getInCriteria() in /home/www/p282743/html/typo3/typo3conf/ext/vidi/Classes/Service/ClipboardService.php on line 51

Any idea, what could has happened?

**Comment by fabarea** [comment]
For some reason the automatic upload to TER of **vidi** 2.0.4 failed. I just retried a new tag push. If it does show up on typo3.org, please take the 2.0.7 directly from github.
