### ISSUE TITLE
Version 3.7.3 not available via Composer

### ISSUE THREAD

**Issue by davidlemaitre** [fabarea/media#123]
I'm using Composer to install extensions. I cant install the latest version 3.7.3 of media extension. This error occurs : 

`
  Problem 1
    - The requested package typo3-ter/media could not be found in any version, there may be a typo in the package name
`

It works with 3.7.2.

**Comment by fabarea** [comment]
3.7.3 was not released on the TER as > 4 was already released. You can however replaced `typo3-ter: media` by `fab/media: 3.7.3` to get it from github.
