### ISSUE TITLE
(TYPO3 7.6) "Error - reference to main window is not set properly!"

### ISSUE THREAD

**Issue by aburg** [fabarea/media#126]
My setup:
- TYPO3 7.6.4
- Vidi 2.0.7
- Media 4.0.2

I found that when I insert a content element of type "Insert records" and within that try to select a record by clicking "Browse for records" and then selecting a record in the popup a javascript error message will show up ("Error - reference to main window is not set properly!") and the record will NOT get selected.

When I do the same with the extension "media" deactivated it works and the main difference here seems to be within the JS function "setFormValueOpenBrowser":

TYPO3 original version builds the url like this: 
`var url = FormEngine.backPath + FormEngine.browserUrl + '&mode=' + mode + '&bparams=' + params;`
(see typo3_src-7.6.4/typo3/sysext/backend/Resources/Public/JavaScript/FormEngine.js)

Media builds the url like this:
`url = FormEngine.backPath + 'browser.php?mode=' + mode + '&bparams=' + params;`
(see html/typo3conf/ext/media/Resources/Public/JavaScript/MediaFormEngine.js)

Though there will probably be a better way to do this, the following fixes that issue for me:

First (in html/typo3conf/ext/media/Classes/Override/Backend/Form/FormResultCompiler.php) change this:
`$pageRenderer->loadRequireJsModule('TYPO3/CMS/Media/MediaFormEngine', 'function(MediaFormEngine) {
            MediaFormEngine.vidiModuleUrl = \'' . BackendUtility::getModuleUrl(VidiModule::getSignature()) . '\';
            MediaFormEngine.vidiModulePrefix = \'' . VidiModule::getParameterPrefix() . '\';
`

to this:
`$pageRenderer->loadRequireJsModule('TYPO3/CMS/Media/MediaFormEngine', 'function(MediaFormEngine) {
            MediaFormEngine.vidiModuleUrl = \'' . BackendUtility::getModuleUrl(VidiModule::getSignature()) . '\';
            MediaFormEngine.vidiModulePrefix = \'' . VidiModule::getParameterPrefix() . '\';
            MediaFormEngine.defaultBrowserUrl = ' . GeneralUtility::quoteJSvalue(BackendUtility::getModuleUrl('wizard_element_browser')) . ';`
(and on top of the file add `use TYPO3\CMS\Core\Utility\GeneralUtility;`)

Secondly (html/typo3conf/ext/media/Resources/Public/JavaScript/MediaFormEngine.js) change this:
`url = FormEngine.backPath + 'browser.php?mode=' + mode + '&bparams=' + params;`

to this:
`url = FormEngine.backPath + MediaFormEngine.defaultBrowserUrl +'&mode=' + mode + '&bparams=' + params;`

**Comment by fabarea** [comment]
Could you make a pull request out of your suggestions? That would help.

**Comment by ghost** [comment]
Using Flux extension, if a flux:field.file is used, Media extension will try to load a browser.php URL (since this is not an inline field) and end up with a 404 error in the popup. In TYPO3 v7.6.4, the browser.php file doesn't exist anymore.
The fix suggested fix the issue
