### ISSUE TITLE
DeleteAction doesn`t work in BE Module

### ISSUE THREAD

**Issue by aWuttig** [fabarea/media#128]
I could not delete a file via BE module. There is no Exception and the AJAX request responses "OK". I only can delete the file via normal FileList Module. What could be the problem?

Best Regards André

**Comment by aWuttig** [comment]
I comment out this line: https://github.com/fabarea/media/blob/master/Classes/Security/FilePermissionsAspect.php#L58 and then i am able to delete files via BE Module. Why you add this SQL IN-statement here?

**Comment by fabarea** [comment]
The line you mentioned is for browsing files within a directory => the recursive option on the top left of the module is **not** checked.

Can you give more context of your problem? I just double checked file removal and it has worked for me. Are you admin or editor as background info? What Media version? File with references **can not** be deleted.

**Comment by aWuttig** [comment]
1. I am Admin
2. I search for the file (e.g.: "foo.jpg") recursively (recursive option is checked!)
3. I found the file (maybe in a subfolder or sub sub folder)
4. I click delete file (trash icon)
5. Some ajax takes places
6. File was not deleted. (File has no FileReferences)

Media Version 3.7.4

For me this fixes the issue, but i think some security issues will there after that:

https://github.com/portrino/media/commit/874ad549e1c55bf9e2466c903b0c84ba74d25fe1

**Comment by fabarea** [comment]
Ah, I think I have an idea why: the flag "recursive" is not transmitted in the Ajax call and the system thinks he's in the context of a selected folder (without the check) => the file to be removed does not belong to the selection => nothing is deleted. I should have a look at it...

**Comment by aWuttig** [comment]
Thank you :)

**Comment by aWuttig** [comment]
Any news on this?

**Comment by fabarea** [comment]
I don't forget you. Just need a slot to dig into that. I hope to have some spare time end of next week.

**Comment by fabarea** [comment]
I will release the next Media now 4.1.0. I exactly went through your steps and could each time delete the file. I suspect it is a Media < 4 issue. I am not maintaining Media anymore for TYPO3 6.2. I could however merge a PR in branch 3.7.x if it makes sense. In this case, I fear that removing as @874ad54 will cause other damages.
