### ISSUE TITLE
Error with DBAL extension

### ISSUE THREAD

**Issue by ghost** [fabarea/media#144]
1. Activate DBAL extension
2. Create a content of type "Images only"
3. Click on "Add image"

Media window opens but displays an error : Oups! Something went wrong with the Ajax request... Investigate the problem in the Network Monitor.

On server side, the error occurs in DBAL : 
`
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1310027933: DBAL fatal error: No handler found in handler_getFromTableList() for: "" (SQL engine parse ERROR: No table name found as expected in parseFromTables()!: near " ") | RuntimeException thrown in file /home/dev/workspace/www/vendor/typo3/cms/typo3/sysext/dbal/Classes/Database/DatabaseConnection.php in line 3102
`

There is no error when DBAL extension is disabled.

TYPO3 7.6.10
Vidi 2.2.0
Media 4.1.0

**Comment by fabarea** [comment]
I don't have time to investigate the issue unfortunately... I am adding a note in the README as a known issue as it is not the first time some report an incompatibility when EXT:dbal is activated.

**Comment by ghost** [comment]
Problem was in class VidiDbBackend.
I fixed the bug and made a pull request.
Seems ok now with dbal.

**Comment by fabarea** [comment]
Thanks, I will integrate the change
