### ISSUE TITLE
static file collection gallery with manual sorting

### ISSUE THREAD

**Issue by exigon** [fabarea/media#147]
Hi, I'm trying to make a photo-gallery limited to a static file collection and preserve the file sorting of the collection, without any luck so far.

I start with the general stuff:

`
        <f:if condition="{vd:content.find(matches: '{storage: 1}', type: 'sys_file')}">
                <f:for each="{vd:content.find(matches: '{storage: 1}', type: 'sys_file')}" as="file">
`

then try to define a typolink with a thumbnail inside (I use the typolink because the thumbnail viewhelper doesn't seem to have a css class option on the link wrapper):

```
                    <f:if condition="{file.metadata.categories}">
                        <f:for each="{file.metadata.categories}" as="category">
                            <f:link.typolink parameter="file:{file.uid}" target="_blank" class="d-imagelink v-{category.title}" title="{file.metadata.title}">
                                <m:file.thumbnail file="{file}" configuration="{width: 150, height: 200}" attributes="{class: 'd-image'}" output="image" />
                            </f:link.typolink>
                        </f:for>
                    </f:if>
```

`

This seems to work but I cannot find a way to limit the output to a static file collection

The following limit returns an error
`<f:if condition="{file.collection.uid} == '5'">`

Also, I cannot seem to pass the static files collection's sorting.

Any suggestions or comments are much appreciated.
Thanks!

**Comment by fabarea** [comment]
To limit the number of files: `{vd:content.find(matches: '{storage: 1}', type: 'sys_file', limit: 5)}"`.
