### ISSUE TITLE
Media backend error for non admin

### ISSUE THREAD

**Issue by ghost** [fabarea/media#148]
When clicking on FILE->Media to open the media backend when logged as a user :

"There must be at least one constraint or a non-empty array of constraints given."

In \Media\Security\FilePermissionsAspect, line 184, a call to logicalAnd function is made with a NULL argument, which triggers the error.

Works ok when logged as admin.

TYPO3 v7.6.10
Media v4.2.0

**Comment by fabarea** [comment]
Let me work on that, I was able to reproduce.

**Comment by fabarea** [comment]
Make sure to update EXT:vidi as well ; git master branch for now.

**Comment by sgrossberndt** [comment]
This fixes the `InvalidNumberOfConstraintsException` 1401289500 for me when accessing the media browser as a non-admin. When are you going to release the new versions of EXT:media and EXT:vidi?

**Comment by fabarea** [comment]
Soon, this is in my pipeline...
