### ISSUE TITLE
Selection in folder tree is ignored

### ISSUE THREAD

**Issue by responseinformationsdesign** [fabarea/media#150]
Since media 4.2.0 all files of a filestore are displayed regardless of the selected folder in the folder tree.

**Comment by mbrodala** [comment]
I can confirm this issue. Via Git bisect the issue can be boiled down to 9132e8e9e06b2cf6186b770b9a12af0cad03e6af.

After further investigation the issue can be narrowed down to the change in the `ext_tables.php`.

**Comment by mbrodala** [comment]
@fabarea I noticed that you have already fixed this issue in master, could you quickly make a new release with this fix? Without this, all folders always show all files which is a breaking issue.

**Comment by fabarea** [comment]
Yes, will release it today. Sorry for the delay.

**Comment by mbrodala** [comment]
Thanks. It took us a while to nail down the issue.
