### ISSUE TITLE
Folders and/or filemounts are ignored in media-module

### ISSUE THREAD

**Issue by papillon6** [fabarea/media#158]
We have different filemounts (and different filestorages). Media shows ALL files of ALL filemounts and folders - no matter which folder or filemount is selected in backend-module.

Using latest media-version 4.3.0 with TYPO3 7.6.11

**Comment by fabarea** [comment]
Mmm... I don't have that. Have you updated Vidi as well? Flushed cache?

**Comment by papillon6** [comment]
Vidi 2.4.0 – Flushed cache, yes.

**Comment by fabarea** [comment]
Will keep an eye on some other running system we have to see if I can confirm the issue or not.

**Comment by papillon6** [comment]
I re-installed vidi. Issue's gone. Thanks!
