### ISSUE TITLE
Different search results depending on backend user group

### ISSUE THREAD

**Issue by Sebobo** [fabarea/media#16]
Hi,

we had the problem in a project that the admins could find all files via the search in the media module, but the other user groups couldn't.
Those files could be found with the normal file list. After opening the files there once, there also appeared in the search results in the media module.
These files also don't have any access restrictions.

Could this be solveable by running the indexing task?
Or is this problem related to something else?

Thanks,
Sebastian

**Comment by fabarea** [comment]
> Could this be solveable by running the indexing task?

Yes that's the solution to run the Indexing Task from the Scheduler.
