### ISSUE TITLE
error if not in Live Workspace

### ISSUE THREAD

**Issue by thomaskieslich** [fabarea/media#174]
Hi, if i try to use media as user with no Live Workspace i got this Error from an Ajax request:

explode() expects parameter 2 to be string, null given
TypeError thrown in file
/Users/thomask/Aktuell/www-mamp/projects/thw/vendor/typo3/cms/typo3/sysext/core/Classes/Database/Query/Restriction/FrontendGroupRestriction.php in line 36.

No Thumnails to shown.

TYPO3: 8.7.1
media/vidi: todays master
Can i Disable Workspaces for Ext:media or is there another Solution.
Thanks, Thomas

**Comment by xperseguers** [comment]
There is a related ticket here: https://github.com/fabarea/vidi/issues/161

**Comment by xperseguers** [comment]
It looks like the whole FAL does not support workspaces at all. I tried to upload a file in File > Filelist from within a workspace. Naturally it is available in LIVE as well.

Now, I try to modify a metadata, it is available in LIVE right away, without publishing.

If I assign categories, they are available in LIVE right away as well.

If I create a new category, in a workspace, it is not available for selection in File > Filelist until it has been published to LIVE as well.

As such, I'd say that the overlay as explained in https://github.com/fabarea/vidi/issues/161 should probably not be done at all.
