### ISSUE TITLE
Storage Selectbox disappear after editing metadata

### ISSUE THREAD

**Issue by PowerKiKi** [fabarea/media#181]
When inserting a media into RTE, the popup will open and show a selectbox for storage, in the upper left corner, as expected:
![image](https://cloud.githubusercontent.com/assets/72603/26723382/9190db24-4794-11e7-8c42-f20ea316ee65.png)

Then, if the user edit metadata of a media and then "close" the media (either via "save and close" or "close" button), it will return back to the media list, but the selectbox for storage will have been replaced with the checkbox "Browse subfolders" and the media list will be empty:

![image](https://cloud.githubusercontent.com/assets/72603/26723417/b7aa2158-4794-11e7-8b55-ad56641ad56f.png)

The expected behavior would be to still have the selectbox available and shows the corresponding media list. So the user does not have to close the window and re-open it everytime he edits a media while inserting it.

Here is the complete demonstration:

![output](https://cloud.githubusercontent.com/assets/72603/26723518/2315ad04-4795-11e7-9c0e-f8decea100b5.gif)

Also I noticed the URL after is missing a parameter that might very well be part of the issue:

Before:
```
/typo3/index.php?M=file_VidiSysFileM1&moduleToken=8881930e0dea389a3d0ed2bb9107c6d6b05bc83b&tx_vidi_file_vidisysfilem1%5Bplugins%5D%5B0%5D=imageEditor&tx_vidi_file_vidisysfilem1%5Bmatches%5D%5Btype%5D=2
```

After:
```
/typo3/index.php?M=file_VidiSysFileM1&moduleToken=8881930e0dea389a3d0ed2bb9107c6d6b05bc83b
```

If you help me get started I might be able to debug further, but I am not sure where to look. Is it actually media or vidi issue ?

**Comment by fabarea** [comment]
The return URL is not correctly set apparently. I would start debugging the issue where the returnUri is generated. https://github.com/fabarea/media/blob/master/Classes/View/Button/EditButton.php#L65
