### ISSUE TITLE
Make the use of TitleMetadataExtractor optional

### ISSUE THREAD

**Issue by tobenschmidt** [fabarea/media#188]
In *ext_localconf.php* an extraction service is registered:

```php
\TYPO3\CMS\Core\Resource\Index\ExtractorRegistry::getInstance()->registerExtractionService('Fab\Media\Index\TitleMetadataExtractor');
```
On upload the TitleMetadataExtractor creates titles for files of type *youtube* based on the filename. Later on in the upload process the title that is provided via YouTube is not used because the file already has a title.

The problem here is that the original title could contain special chars that are removed by TitleMetadataExtractor.

An example:
https://www.youtube.com/watch?v=n6-9hN9EzNI

Original title:
*Links bewegt (3): Wie "Mieten-Kalle" sich nicht aus seiner Wohnung vertreiben ließ*

Title in TYPO3 CMS 7.6 **with** TitleMatadataExtractor:
*Links bewegt 3 Wie Mieten Kalle sich nicht aus seiner Wohnung vertreiben ließ*

Title in TYPO3 CMS 7.6 **without** TitleMatadataExtractor:
*Links bewegt (3): Wie "Mieten-Kalle" sich nicht aus seiner Wohnung vertreiben ließ*

As the ExtractorRegistry does not offer a method to unregister an extraction service I suggest to make the use of TitleMetadataExtractor optional via extension configuration.

**Comment by fabarea** [comment]
Yes, we could do that. Could you provide a PR for that?
