### ISSUE TITLE
Search in Module filelist fails

### ISSUE THREAD

**Issue by teaminmedias-pluswerk** [fabarea/media#204]
After installing the "Media management" extension in typo3 9.5.7, the search in the "Filelist" module returns the following error:
Oops, an error occurred!
Invalid file search ordering given table: "sys_file", field: "uid", direction: "DESC".

**Comment by aceArt-GmbH** [comment]
@teaminmedias-pluswerk same issue here. The default sort order of the TCA was changed from "name DESC" to "uid DESC" by the media plugin. You can solve this bug by overwriting the default sort order again in your extension. Just create a sys_file.php in your extension under the path _Configuration/TCA/Overrides_ with the content:

```<?php
if (!defined('TYPO3_MODE')) die ('Access denied.');

$tca = [
    'ctrl' => [
        'default_sortby' => 'name DESC'
    ]
];

\TYPO3\CMS\Core\Utility\ArrayUtility::mergeRecursiveWithOverrule($GLOBALS['TCA']['sys_file'], $tca);
```

Don't forget to add the media constraint at your ext_emconf.php file to make sure that your extension is loaded after the media extension.

That fix isn't perfect. It changes the behavior of the sort order at the media table. But it solves the issue for me.

**Comment by fabarea** [comment]
It has been fixed here https://github.com/fabarea/media/commit/43136f95b6881e7fdc4639620b5c89d563f5e341
