### ISSUE TITLE
Export XLS/XML/CSV via mass action leads to TYPO3 Error at TYPO3 9.5

### ISSUE THREAD

**Issue by mschmitz89** [fabarea/media#205]
When using the Buttons "Export XLS", "Export XML" and "Export CSV" at the bottom of the list view via Button "For all rows" you get the same TYPO3 error when using the latest vidi extension at version 3.3.0:

`Return value of Fab\Vidi\Tca\GridService::areFilesIncludedInExport() must be of the type array, boolean returned`

When downgrading to vidi 3.1.1 this works fine.

**Comment by fabarea** [comment]
I fixed it in master https://github.com/fabarea/vidi/commit/53fe6df7cf38dbc0a3dae4d72a2008166a5511cb
