### ISSUE TITLE
Command fileCache:flushProcessedFiles can delete document root

### ISSUE THREAD

**Issue by lorenzulrich** [fabarea/media#209]
The `flushProcessedFiles` command flushes all processed files of all storages.

To find the appropriate folder, the value set in the storage record (field `processingfolder`) is used. If this field is not set (not a mandatory field), the default processed folder is used.

Media then looks up the `publicUrl` of this folder:

https://github.com/fabarea/media/blob/59da861327583c1a0133c36066b7d843d0d99788/Classes/Command/FileCacheCommandController.php#L60

If you have non-public folders, such as folders for protected storages, this code will return `null`. `null` will then be concatenated with `PATH_site`. Therefore the document root folder will be cleared. Depending on your setup, it can have very serious effects, but in any case it will render the installation unusable.

**Comment by fabarea** [comment]
Resolved via https://github.com/fabarea/media/pull/222/commits/f747d1dda029640e9c65a1c3ef5012840ae7b048
