### ISSUE TITLE
[FEATURE] Folder tree - configure Media to hide the tree for basic Editors

### ISSUE THREAD

**Issue by fabarea** [fabarea/media#34]
Check if possible to configure the module to hide the tree for basic Editor users for instance. Reduce visual "complexity". I don't know if that's possible without changing the Core.

**Comment by fabarea** [comment]
Implemented and merged on "development", soon to be merged into "master".

**Comment by Mo0812** [comment]
Hey fabarea, how can i edit what's shown on a filelist and what's not?
