### ISSUE TITLE
DataHandlerHook produces fatal error in workspace

### ISSUE THREAD

**Issue by lorenzulrich** [fabarea/media#39]
When the user is in a workspace and saves a Text & Images CE, on saving a fatal error occurs:

```
[Tue May 19 15:55:34 2015] [error] [client 127.0.0.1] PHP Catchable fatal error:  Argument 1 passed to TYPO3\\CMS\\Media\\Hook\\DataHandlerHook::isSoftReferenceImage() must be of the type array, boolean given, called in /home/www-data/www/htdocs/typo3conf/ext/media/Classes/Hook/DataHandlerHook.php on line 215 and defined in /home/www-data/www/htdocs/typo3conf/ext/media/Classes/Hook/DataHandlerHook.php on line 248, referer: https://www.domain.tld/typo3/alt_doc.php?returnUrl=%2Ftypo3%2Fsysext%2Fcms%2Flayout%2Fdb_layout.php%3Fid%3D531&edit[tt_content][33122]=edit
```

Didn't have time to check it yet, but I will.

**Comment by BoBaH83** [comment]
in Workspace it's not working even if I try to open the file browser (element browser) on any CE with files related. But it seems to be something wrong in "vidi" extension not in "media" ...
PHP Catchable Fatal Error: Argument 2 passed to TYPO3\CMS\Vidi\Domain\Model\Content::__construct() must be of the type array, boolean given, called in /var/www/htdocs/current/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 4371 and defined in /var/www/htdocs/current/typo3conf/ext/vidi/Classes/Domain/Model/Content.php line 47

Do you think its the same issue? did you already had the time to check it?
this seems to be related:
https://github.com/fabarea/vidi/issues/14

**Comment by fabarea** [comment]
Pull request has been merged
