### ISSUE TITLE
FilePermissionsAspect::respectFileMounts(...) not working, users can see all files of storage(s)

### ISSUE THREAD

**Issue by hnadler** [fabarea/media#5]
In current master (vidi and media) - at least with PHP 5.4 - users filemounts are not respected. If a user has a filemount he can see the whole storage. Constraints are passed by signalSlot to

``` php
protected function respectFileMounts(Query $query, $constraints) ...
```

and in the end happens this:

``` php
$constraints = $query->logicalAnd(
    $constraints,
    $constraintsRespectingFileMounts
);
```

This wont work, at least in PHP 5.4. The $constraints variable is not modified in any way.

**Comment by fabarea** [comment]
Ok, let make a return of $statement in this case. Before I further proceed, could you check out branch "development" of media + vidi and let me know.
