### ISSUE TITLE
Can't choose images from RTE integration - instead edit mode opens

### ISSUE THREAD

**Issue by borishinzer** [fabarea/media#52]
While using media within normal images I can select an image by clicking on it or choosing the row action. When I try to do the same within the RTE integration I get the image edit mode, where I can crop the image. I'm unable to select the image. Also I don't have the ability to choose several images and use the row action method.

**Comment by fabarea** [comment]
> When I try to do the same within the RTE integration I get the image edit mode, where I can crop the image. I'm unable to select the image.

Use the Link Creator instead for linking images in the RTE

![2015-06-12_1006](https://cloud.githubusercontent.com/assets/620730/8159173/636da01c-1364-11e5-92b3-caf411098520.png)

> Also I don't have the ability to choose several images and use the row action method.

That's true, that is missing. A patch is required. Can you create a new issue for that?

BTW, try master of Media / Vidi (soon to be released to the TER), it has supports for the folder tree like the "filelist".

**Comment by borishinzer** [comment]
I know that I can link images in RTE, but I want to add them inline. That's what is missing.

**Comment by fabarea** [comment]
What do you mean by "add inline"? If you open the "Image editor" in the RTE > click on an image > click on the upper left icon (without resizing), it will add the image into the RTE. Is perhaps the button not explicit enough?

https://www.dropbox.com/s/tfivzdspd4ij7tv/Screenshot%202015-06-15%2014.25.32.png?dl=0

**Comment by borishinzer** [comment]
Sorry, I can't access your Screenshot. Please take a look at mine:
https://owncloud.web-vision.de/index.php/s/H4D426dPydCLKu4

In screenshot 3 there is no icon to add the image to the RTE. Nevertheless I found out, that from there I can drag'n'drop image over to the RTE which was a surprise for me.

**Comment by fabarea** [comment]
Yeah, then click on the icon below and the image should be inserted in the RTE.

![2015-06-17_0906](https://cloud.githubusercontent.com/assets/620730/8201336/3acc673e-14d0-11e5-81a7-b420e6bce18b.png)
