### ISSUE TITLE
Handling of files copied outside of TYPO3 backend

### ISSUE THREAD

**Issue by ghost** [fabarea/media#60]
Hi,

When I copy an image file in a directory without using TYPO3 backend (e.g. using "cp" command directly on the server), the images are not taken in account by the media extension.
In the filelist view, I see the images, but not in the media extension, even after clicking on the refresh button at the top right of the media module.
When I upload an image file using the media module, it's ok.
Is it the expected behavior ?

Regards,
Fabrice

**Comment by fabarea** [comment]
Image, should be indexed in the scheduler or - if you use the master of Media / Vidi you can click on the folder tree and files will be indexed on the fly.

**Comment by ghost** [comment]
With the master version, it is no more possible to select a storage in the media module; searching an image starts at the fileadmin root.
How to filter the search using a subdirectory of fileadmin ? Is it planned to have to possibility to select a folder ?

**Comment by fabarea** [comment]
There is the recursive browsing option on the top, when you tick the checkbox, it will search into the subfolders from where you have selected the folder. Furthermore, you can switch back in the EM in the previous view where you have no folder tree - if needed.

![mediamodule](https://cloud.githubusercontent.com/assets/620730/8717429/dfb4b170-2b9b-11e5-827a-d793900acf14.png)

**Comment by ghost** [comment]
Thanks for those information.
In fact what I want to do is selecting an image for a page content element (for example a simple image content).
In that case, after clicking on the "add image" button, there is no folder tree in the popup selector, and there is a JS error preventing the display of the dataTable (with the latest iceweasel).

![image_select](https://cloud.githubusercontent.com/assets/4995658/8718251/379cf4b8-2ba3-11e5-8f3c-b5afe1946cff.png)

It is indeed working in chrome, but is it possible to have the folder tree for this popup selector ?

**Comment by ghost** [comment]
It works after clearing the browser cache. I can see the select list with the file storages.

**Comment by fabarea** [comment]
ok, good
