### ISSUE TITLE
Image displayed in full size in media module after upload

### ISSUE THREAD

**Issue by ghost** [fabarea/media#61]
In the media module, after uploading an image, it is displayed as full size instead of a small preview.

I use TYPO3 6.2.14.

**Comment by fabarea** [comment]
please, check your Graphicsmagick / ImageMagick configuration

**Comment by ghost** [comment]
All tests are successfull in the install tool. Which specific configuration should I check ?

**Comment by fabarea** [comment]
flush sys_file_processed table and _processed directory, should work.

**Comment by ghost** [comment]
This problem sometime happens, but unfortunately I can't delete processed files and their references after each upload.

**Comment by ghost** [comment]
This problem doesn't happen in file->list view.
It happens in the vidi popup (after clicking on the "add image" button from the image content element for example), when uploading the attached image for example.
![1600x1200_fj_aquaswing_bouclesdoreilles](https://cloud.githubusercontent.com/assets/4995658/8727351/7f404ee6-2bdf-11e5-909e-23d17ba4880e.jpg)

**Comment by fabarea** [comment]
ok, weird. Have to further investigate.

**Comment by fabarea** [comment]
> This problem sometime happens 

As the problem does not always occur, can you send me a faulty file for further debug in my end? Please, put that file on some file sharing service. I tested with the image given above but could not reproduce.

<img width="450" alt="screenshot 2015-10-28 11 50 05" src="https://cloud.githubusercontent.com/assets/620730/10786368/17137f50-7d6a-11e5-9d58-313ad2a41872.png">
