### ISSUE TITLE
Mass edit link

### ISSUE THREAD

**Issue by georgringer** [fabarea/media#63]
It would be very awesome to have a mass edit functionality of medadata.

How I imagine it:
- Records are checked like for csv export
- After selecting edit, the link to FormEngine with the uids, e.g. &edit[sys_file_metadata][123,456,789]=edit

**Comment by fabarea** [comment]
There is an edit icon on the top for mass-editing. You can either mass-edit a selection or per clicked raw. Mass-editing works for relations like "categories" or scalar value like "title". Let me know if it does not work for you.

![mediamodule](https://cloud.githubusercontent.com/assets/620730/8929257/56a6a48c-3524-11e5-9002-58f1885f159f.png)

**Comment by fabarea** [comment]
Closing the ticket for now, don't hesitate to re-open in case of issues.

**Comment by georgringer** [comment]
thanks for your fast answer! i would like to see a link which leads me to the mass edit of FormEngine

**Comment by fabarea** [comment]
The request goes through the [Content Controller](https://github.com/fabarea/vidi/blob/master/Classes/Controller/Backend/ContentController.php#L111) with then call the ContentRepository->update() line 149 which then call the [DataHandler](https://github.com/fabarea/vidi/blob/master/Classes/Domain/Repository/ContentRepository.php#L486) of TYPO3
