### ISSUE TITLE
[Bugfix] Respect renderMode "tree" 

### ISSUE THREAD

**Issue by mischka** [fabarea/media#64]
The category-view (metadata.categories) should render the category-tree not only a flated list.
This is important if you have Subcategories with the same name.

**Comment by fabarea** [comment]
I know, I have this task on my todo list for some time. Have you heard anything regarding the tree "widget" in the Core. We want to move away from the current ExtJS approach. Is it some replacement pointing at the horizon?

**Comment by mischka** [comment]
I don't know the tree widget, but how can you integrate this in your extension? You use your own views and templates to render records (I did not find a widget in the fluid-docs).
Will you change vidi to use another JS-Framework or what is on your roadmap?

**Comment by fabarea** [comment]
I am waiting for now what the Core will decide and don't rush a solution (particularly JS-based). I was thinking I could simply work on the indentation of the checkbox to mimic the tree.

**Comment by mischka** [comment]
Maybe you can use this pullrequest https://github.com/fabarea/vidi/pull/53 as a temporary solution
