### ISSUE TITLE
Crop and Effects buttons not working

### ISSUE THREAD

**Issue by lroovers** [fabarea/media#65]
First complements for the nice extension. I see you've already done a lot of work.
Especially the posibility to manage variants is attractive for us.
Unfortunalety I found some bugs (either in the code or in the manual).
I can add images, select though RTE and more. But cropping tab/button does not work and Effect Button does not work. SImply doíng nothing when I click.
I see no js errors or failures on file loading.
Resizing on the same page works fine.

![vidi_-_2015-08-15_12 21 27](https://cloud.githubusercontent.com/assets/13808494/9288473/ba760a98-4348-11e5-83da-cf9ecb72fe8b.png)

One other thing is not working, I will add a separate issue for that. - 'variants are missing'. Might be related.
By the way: I tested in actual versions of Firefox, Chrome and IE / Win 8,.1

**Comment by fabarea** [comment]
Feature was removed due to lack of time.
