### ISSUE TITLE
Not sanitized Title metadata?

### ISSUE THREAD

**Issue by zelcode** [fabarea/media#67]
Hi,

After upload Title metadata is sanitized (no national characters or umlauts), it would be better without sanitization.

Or if you can point me in right direction how to get unsanitized file name for Title metadata.

Regards

**Comment by fabarea** [comment]
Here's in the method where the title is extracted. 
https://github.com/fabarea/media/blob/master/Classes/Index/TitleMetadataExtractor.php#L109

If you have any improvement let me know.

**Comment by fabarea** [comment]
As implemented, the title is drifted from the **file name** which is already stripped from accent at this point. So we don't have this info available. However, if the title is contained in the metadata of the file it could be retrieved thanks to EXT:metadata which has a higher precedence in the metadata extraction as EXT:media. Try this.
