### ISSUE TITLE
[Bugfix] change-storage run into 404-Error

### ISSUE THREAD

**Issue by mischka** [fabarea/media#69]
On my nginx the change-storage-Action run into a 404-Error. The reason is, that the path is wrong.
The problem in the /? in path;

```
/typo3/mod.php/?M=user_MediaM1&moduleToken=c69aed168026fda4274c3207281130944283e183&tx_media_user_mediam1%5Bcontroller%5D=Asset&tx_media_user_mediam1%5Baction%5D=editStorage&tx_media_user_mediam1[matches][uid]=488&iSortCol_0=&sSortDir_0=as
```

The https://github.com/derek-watson/jsUri can only handle with absolute URL's you are using a relative one in the media.js on line 11257;

```
$(this).attr('href') // => mod.php?M=user_MediaM1&moduleToken=bb2a948d40db70eee81f8f1da2f6a3dd43b32c3e&tx_media_user_mediam1%5Bcontroller%5D=Asset&tx_media_user_mediam1%5Baction%5D=editStorage
```

you should use

```
this.href // => http://localhost/typo3/mod.php?M=user_MediaM1&moduleToken=bb2…ediam1%5Bcontroller%5D=Asset&tx_media_user_mediam1%5Baction%5D=editStorage
```

**Comment by fabarea** [comment]
What version? I suspect it is gone in master.

**Comment by fabarea** [comment]
I have just double checked and I don't get the "/?" in the master.

**Comment by mischka** [comment]
hello I use version 3.5.3

**Comment by mischka** [comment]
I think the problem is still there

https://github.com/fabarea/media/blob/master/Resources/Public/Build/media.js#L11256

because $(this).attr('href') retrieves an relative url but https://github.com/derek-watson/jsUri https://github.com/fabarea/media/blob/master/Resources/Public/Build/media.js#L11275 can only handle absolute url's so you should use this.href instand of $(this).attr('href')

**Comment by mischka** [comment]
@fabarea plz check this again

**Comment by fabarea** [comment]
$(this).attr('href') -> returns mod.php?M=blabla... for me and this should work, not?

this.href -> as suggested above, returns an object in my case.

Let experiment again...

**Comment by mischka** [comment]
yes thats correct, but you use new Url here https://github.com/fabarea/media/blob/master/Resources/Public/Build/media.js#L11275 and this retrieves a wrong url (/typo3/mod.php/?M=user_MediaM1&modul) because https://github.com/derek-watson/jsUri can only handle absolute urls
