### ISSUE TITLE
PHP Error after install

### ISSUE THREAD

**Issue by digedag** [fabarea/media#70]
After extension install in TYPO3 6.2 I get the following error when I click on BE module Media:

```
Fatal error: Cannot make non static method TYPO3\CMS\Core\Type\Enumeration::getConstants() static in class Fab\Vidi\Module\ConfigurablePart in /path2t3/typo3conf/ext/vidi/Classes/Module/ConfigurablePart.php on line 50 
```

This method in _Fab\Vidi\Module\ConfigurablePart_ is wrong:

``` php
    static public function getConstants($include_default = FALSE) {

        // Must be instantiated once to load the values.
        if (is_null(self::$instance)) {
            self::$instance = GeneralUtility::makeInstance('Fab\Vidi\Module\ConfigurablePart');
        }
        return parent::getConstants($include_default);
    }
```

This is the signature of getConstants in _TYPO3\CMS\Core\Type\Enumeration_:

``` php
public function getConstants($include_default = FALSE)
```

If you really need a static getContants() in ConfigurablePart, it should be renamed. After that it is possible to call _getContants()_ on _self::$instance_.

I use PHP Version 5.5.15.

**Comment by fabarea** [comment]
Will be resolved through https://github.com/fabarea/vidi/issues/63
