### ISSUE TITLE
[FEATURE] Add alt attribute editing

### ISSUE THREAD

**Issue by Nioldur** [fabarea/media#73]
Alt attribute of image files should be shown in Vidi grid by default and also get used when adding an image in the RTE. If that is already possible, i would be thankful for pointing me to a doc.

**Comment by fabarea** [comment]
alt attribute best works if image has a title. This was actually already working in the Media module like that, **now** "alt" attribute is also added in the RTE (thanks for pointing out!) under the condition the image has a title, otherwise it will be void.
