### ISSUE TITLE
Access control / Filemounts

### ISSUE THREAD

**Issue by wegewerk-mkb** [fabarea/media#74]
We have a site with ~30,000 files and used filemounts in the past to control who has access to what.
Is there any way to control wich files a backend user can access - preferably with our existing filemounts?

**Comment by fabarea** [comment]
I have just released a new version of Media (3.6.0) which support FileMounts. Can you have a look, it should appear on the TER soon. Make sure to also upgrade, Vidi (1.0.0) update the database and clear all possible caches.

If you don't want to use the file mounts to handle control access, you can use different storage per group. Both approaches are OK.
