### ISSUE TITLE
Access control with Filemounts not working in MediaFilePicker

### ISSUE THREAD

**Issue by wegewerk-klr** [fabarea/media#77]
I got 1 filestorage configured and multiple filemounts which are bound to specific usergroups.
when i open the media browser it shows this error:
#1375955684: You are not allowed to access the given folder: ""

this is not much of a problem, as when i click on the filemount in the directory tree, it will load the correct path specified in the filemount.

however if i open the filebrowser from a tt_content to add a relation, it throws the same error, but with no directory tree to click on the filemount.

the only way i could prevent this error is creating a storage for every filemount i have.
is there any other solution for this to work with 1 storage and multiple filemounts?

thx,
Kai

**Comment by fabarea** [comment]
What version do you use?

> however if i open the filebrowser from a tt_content to add a relation...

The Core filebrowser I am assuming you talk about. There could also be the Media Picker but it must be activated in the EM. Well... it looks more as configuration issue as really related to Media. I can not say much knowing so little about you environment I must admit.

What I can confirm, it works for me having one storage and multiple mount points.

**Comment by wegewerk-klr** [comment]
i use the newest version of the extension (v3.6.0) and the typo3 version 6.2.15.
and i use the media filepicker (the one the extension provides).
the other configurations and extensions installed in the system should not interfere with media.

i debugged through the code and it seems that the filepicker, when called initially, doesn't set the path to the filemount correctly, therefore throws the error that i don't have access to the root folder of the storage.

**Comment by fabarea** [comment]
> doesn't set the path to the filemount correctly

Ok, thanks for digging, do you have pointer where it "doesn't set the path correctly"?

**Comment by fabarea** [comment]
FYI, I will make a new TER release today which may improve the situation.

**Comment by wegewerk-klr** [comment]
thank you for that info.
with version 3.6.1 it works like a charm.
