### ISSUE TITLE
FileUpload for non-admins not working

### ISSUE THREAD

**Issue by wegewerk-klr** [fabarea/media#81]
the fileupload for non-admins (i have set the access rights to the media module) fails with the following error message:
#1294586448: Access Error: You don't have access to this module. (More information)

in the stackitrace, i found this:
1 TYPO3\CMS\Extbase\Core\ModuleRunner::callModule("user_MediaM1")

the access right "user_MediaM1" is never given... instead the "Media" module access right got the value "file_VidiSysFileM1".
As i googled this issue i found that there was "Media (extra)" which was responsible for setting the access right "user_MediaM1" but in the new version, this isn't available.

thanks,
kai

**Comment by fabarea** [comment]
Media (extra) was renamed differently. Check the last entry. It should be better documented I agree...

<img width="521" alt="screenshot 2015-10-14 21 28 24" src="https://cloud.githubusercontent.com/assets/620730/10495141/9f7513b4-72ba-11e5-9670-ffc9762fa16b.png">

**Comment by wegewerk-klr** [comment]
great, now it works. Could you position it under the main access right? perhaps by the name "File->Media Ext...." so the permission is easier to find.

or document it :p
thank you very much
