### ISSUE TITLE
Media file picker: folder tree, edit from file reference

### ISSUE THREAD

**Issue by wegewerk-mkb** [fabarea/media#82]
Hi there.
Two questions regarding the media file picker:
1. From #77 "In the Media popup, the folder tree will not be displayed because of iframe issue." Can you tell if the folder tree issue can be resolved in the near future?
2. Is it possible to add a edit link at the file reference?
If you add a new Image, you can edit the file in the media file picker, but if you want to edit the file from an existing file reference you habe to search for the file first.

**Comment by fabarea** [comment]
1. Not resolvable for 6.2 but for 7 perhaps, I would need to investigate if things have change in that matter. I am not sure to be honest...
2. I don't see exactly what "edit from an existing file reference". Little screenshot could help?

**Comment by wegewerk-mkb** [comment]
Thank you for your fast replies!

What I meant was: After adding an file/image to a content object, some meta data kann be overriden, but an edit button - at the red rectangle position - to be able to add categories for example would be nice. 
![2015-10-16-metadata](https://cloud.githubusercontent.com/assets/3597270/10536201/9e055ee6-73e9-11e5-9420-11189993b094.png)
At the moment users have to copy the filename and search it.

**Comment by fabarea** [comment]
Mmm... it is not an easy thing to do, I fear. I understand the usefulness of course but it should be provided by the Core. If you want to provide with the beginning of a patch, I will gladly review it.
