### ISSUE TITLE
Media file picker ignores filemount

### ISSUE THREAD

**Issue by wegewerk-mkb** [fabarea/media#86]
There is one storage (/fileadmin) and multiple filemounts. While the module shows only the correct filemount for the user, the media file picker will show at first every file in the storage:
![2015-10-19-mfp-01](https://cloud.githubusercontent.com/assets/3597270/10578588/5d08f768-7673-11e5-9f2b-24b29d3029c1.png)
After editing and closing a file, the view changes and seems to respekt the filemount.
![2015-10-19-mfp-02](https://cloud.githubusercontent.com/assets/3597270/10578590/5f032c1e-7673-11e5-84a8-3b78efd4f828.png)
v3.7.0

**Comment by fabarea** [comment]
Since we don't have the folder tree in the Media File Picker (unfortunately because of iframe issue), as a User I would expect to see every file. Do you agree? 

I think I will hide the first drop down menu and make it "browse sub-folders" checked by default.

**Comment by wegewerk-mkb** [comment]
Since the filemounts are used to controll access to files, I would not like to show all files of the _storage_. Showing all files of the _filemount_ would be the expectet result - which is what happens after editing and closing a file.

**Comment by fabarea** [comment]
I am more precise: show all files that the BE user has access => taking into account the file mounts.
