### ISSUE TITLE
Store "Browse sub-folders" state in selection

### ISSUE THREAD

**Issue by lorenzulrich** [fabarea/media#99]
The selection currently doesn't store the state of the "browse sub-folders" checkbox. Since this affects the files displayed in the same way as a filter does, it would be good to save this state.

**Comment by fabarea** [comment]
We have room for improvement regarding Selection, saving the browse sub-folder is one of them. On the top of that, I also would like to persist the order of the Selection.

**Comment by fabarea** [comment]
The first commit is wrongly associated to this ticket. 

However, I changed the default. We now browse recursively by default which looks more natural if I believe several users feedback I got.
